language: python
services: docker
git:
  depth: 5
cache:
  pip: true
  directories:
  - "$HOME/bin"
  - "$HOME/.download"
matrix:
  include:
  - python: 2.7
  - python: 3.6
  - env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
  - os: osx
    language: generic
    env: PYENV=py27
  - os: osx
    language: generic
    env: PYENV=py36
before_install:
- travis_retry bash <(curl -s https://raw.githubusercontent.com/limix/travis-tools/master/get-travis-tools.sh)
- travis_retry travis/before-install.sh
install:
- travis_retry travis/install.sh
script:
- travis_retry travis/script.sh
after_success:
- travis_retry travis/after-success.sh
notifications:
  email:
    recipients:
    - danilo.horta@gmail.com
    on_success: change
    on_failure: always
deploy:
  provider: releases
  api_key:
    secure: VfiUi5K+QUR1pqvsWLXhH6bBP3EsmlrObX2u8K836xB8JRTQFo0aMzVZqRv56/xM4PvN7diTq/UWOG+vx9FsEdqlgbiaYfoc+0vBCh9cfVtBMx/9phykupDw+/S2F6+ta0Ps5aMmkmDndoqs6Rh4ow83TPuiNKiMrZrV73rTK8556c8lAoBidqPYvMVpdVCBVijqhsWfAUrr7N9EcnirRsM8vTmFk7N5iEE58icGc2ZmBlYapKPTsRi2lpSCvUkubyGoqkunwqtRWPjGnpPeY+2Lv3w43W9E63XHQ0CBAIFf87AWFangsF/7kVwGsG24+2BFKS/P7ebyMH4HKTJlfJulM7IBQSCvmhlY8La2G/HVenVxqaIEmaPepc7yqW0LWeYWiGSoeGbtx27n955JOWRBFX8+T/BpSryGFTSr4sg1+pBoL8frbM1vDz5kToZiULa7u05d2BC3e8DclsV0QdI2q+N/N82NgDVqEcHt5V7pBfQUYMybqk5QrigCSHWN9zDDQGKJBLO+NojwQCYEuM8Pels1tfb/CSVyJdP3VmakdSA69ZO2A6XTzACol6Uh5pxMe67kwyYVt3s4A4l8HiK/KRsZFhENgbHGgs9yIklYfOFdL7IiJ5hHyS/uiWs7s2yUB9eSk41cuLTxihVvpdS/V7gIK9kOg7KG7ZnfQcg=
  file: ''
  on:
    repo: limix/scipy-sugar
    branch: branch
env:
  global:
  - secure: enuW0ZSAo3Wpw58yk6lcSrLP6wgA9zT3/us5nosY/g6UF3//WjdslIB2qfuLv2gCZ5cH4Q2WDXRcXVijnqrruMHHjCpaXWWC5GGVjYWqtdc1OkIIFSKsxqKIVc8ykK7unONgH//vYmQc17M50li/bUveBz1tfnR8empQGtDttNuul313R5o6YLPtWzjJvd/FL1kX1ELa0DMha+pOCBhPLYZZMnxnYtaNqZQYUHnQKA+pnFYQ0icuSfCIbe0LsQShdz8zAuv6F0MXh+f0/kP1Hq74BZORA44zqlpJRARM98ov/jdj65TNA6+D8tVA3ksJlYzxlmA9dJ6LsIU6Y9cncfGis1UsEyP/j/MfJxw3O1KPoVDC+7QLWbbe7zLVK3HLRmhGZk6yWB+X+S01IiJdRqY++A1iJO7Jrkb3eFp/d9i8iDYiFgCHbItbHeKCY0f2RuR4TEwiaInBfpVsgINWJrOsw3W9Y/HFeF1RzvHVjqHFToruoz1i7ZPTZsUWJdVYG4qyEOs8BNdmPlQTzLp3lOtcULP91Bze+s8IlV4m3GPC4I6CXrIiI7+hbEsWhjpNJ1fsJIQVlGFnQzHT2F52jXWOrEKB7JeZx6emtZgOeQq8+dcXsMHU7x7SySalW7Tf+Qq4GjF1tYcH1q4KNuYUSuV7D7hI3yl8S0GKvLha5k0=
  - PKG_NAME=scipy_sugar
