os: linux
language: python
sudo: false
python: 3.6
env:
  - PKG_NAME=optimix
addons:
  apt:
    packages:
    - pandoc
script:
  - bash <(curl -fsSL https://raw.githubusercontent.com/horta/ci/master/travis.sh)
notifications:
  email:
    recipients:
    - danilo.horta@gmail.com
    on_success: never
    on_failure: always
